export class Champion{
    idMongo?: string
  id?: number
  nom?: string
  sexe?: string
  paysID?: string
  nvPaysID?: string
  dateChangementNat2?: Date
  dateNaissance2?: Date
  dateChangementNat?: string
  dateNaissance?: string
  lieuNaissance?: string
  grade?: string
  clubs?: string
  taille?: number
  poids?: number
  tokuiWaza?: string
  mainDirectrice?: string
  activite?: string
  forces?: string
  idole?: string
  idole2?: string
  idole3?: string
  idole4?: string
  idole5?: string
  idole6?: string
  idole7?: string
  lidole2?: string
  lidole3?: string
  lidole4?: string
  lidole5?: string
  lidole6?: string
  lidole7?: string
  anecdote?: string
  phrase?: string
  vuPar?: string
  site?: string
  idold?: string
}